import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';
import { createHash } from 'crypto';
import pino from 'pino';

const logger = pino();

export interface PDFArtifact {
  id: string;
  jobId: string;
  type: 'REPORT' | 'CALCULATION_SHEET' | 'SUMMARY';
  filePath: string;
  sha256: string;
  createdAt: string;
  sizeBytes: number;
}

export class PDFGenerator {
  private outDir: string;

  constructor() {
    this.outDir = process.env.ARTIFACTS_DIR ?? path.join(process.cwd(), 'artifacts');
    if (!fs.existsSync(this.outDir)) {
      fs.mkdirSync(this.outDir, { recursive: true });
    }
  }

  /**
   * Generate a PDF report with sections and citations
   */
  async generateReport(
    jobId: string,
    title: string,
    sections: { heading: string; body: string }[],
    citations?: { documentTitle: string; location: string; excerpt: string }[]
  ): Promise<PDFArtifact> {
    return new Promise((resolve, reject) => {
      try {
        const fileName = `report_${jobId}_${Date.now()}.pdf`;
        const filePath = path.join(this.outDir, fileName);
        
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs.createWriteStream(filePath);
        
        doc.pipe(stream);
        
        // Title
        doc.fontSize(24).text('SIH 2026 Sovereign AI Workbench', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(18).text(title, { align: 'center' });
        doc.moveDown(1);
        
        // Disclaimer
        doc.fontSize(10).text('NOTE: This document was generated by an AI-assisted system. All engineering conclusions must be independently verified.', {
          align: 'center'
        });
        doc.moveDown(1);
        
        // Generated timestamp
        doc.fontSize(10).text(`Generated: ${new Date().toISOString()}`);
        doc.moveDown(1);
        
        // Sections
        for (const section of sections) {
          doc.fontSize(14).text(section.heading, { underline: true });
          doc.moveDown(0.3);
          doc.fontSize(11).text(section.body);
          doc.moveDown(0.5);
        }
        
        // Citations
        if (citations && citations.length > 0) {
          doc.addPage();
          doc.fontSize(16).text('Citations', { underline: true });
          doc.moveDown(0.5);
          
          for (const citation of citations) {
            doc.fontSize(11).text(`• [${citation.documentTitle}] at ${citation.location}`, { continued: true });
            doc.fontSize(10).text(` "${citation.excerpt.slice(0, 100)}${citation.excerpt.length > 100 ? '...' : ''}"`);
            doc.moveDown(0.3);
          }
        }
        
        doc.end();
        
        stream.on('finish', () => {
          const buffer = fs.readFileSync(filePath);
          const sha256 = createHash('sha256').update(buffer).digest('hex');
          
          resolve({
            id: `pdf_${Date.now()}`,
            jobId,
            type: 'REPORT',
            filePath,
            sha256,
            createdAt: new Date().toISOString(),
            sizeBytes: buffer.length
          });
        });
        
        stream.on('error', (error) => {
          reject(new Error(`PDF_GENERATION_ERROR: ${error.message}`));
        });
        
      } catch (error: any) {
        reject(new Error(`PDF_GENERATION_ERROR: ${error.message}`));
      }
    });
  }

  /**
   * Generate a simple calculation sheet PDF
   */
  async generateCalculationSheet(
    jobId: string,
    title: string,
    calculations: { parameter: string; value: number; unit: string }[],
    result: { name: string; value: number; unit: string; status: string }
  ): Promise<PDFArtifact> {
    return new Promise((resolve, reject) => {
      try {
        const fileName = `calc_${jobId}_${Date.now()}.pdf`;
        const filePath = path.join(this.outDir, fileName);
        
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs.createWriteStream(filePath);
        
        doc.pipe(stream);
        
        // Title
        doc.fontSize(20).text('Engineering Calculation Sheet', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(16).text(title, { align: 'center' });
        doc.moveDown(1);
        
        // Input Parameters
        doc.fontSize(14).text('Input Parameters', { underline: true });
        doc.moveDown(0.3);
        
        for (const calc of calculations) {
          doc.fontSize(11).text(`${calc.parameter}: ${calc.value} ${calc.unit}`);
        }
        
        doc.moveDown(1);
        
        // Result
        doc.fontSize(14).text('Result', { underline: true });
        doc.moveDown(0.3);
        doc.fontSize(11).text(`${result.name}: ${result.value} ${result.unit}`);
        const statusColor = result.status === 'COMPLIANT' ? 'green' : 'red';
        doc.fontSize(11).text(`Status: ${result.status}`);
        
        doc.moveDown(1);
        doc.fontSize(10).text(`Generated: ${new Date().toISOString()}`);
        doc.fontSize(10).text(`Job ID: ${jobId}`);
        
        doc.end();
        
        stream.on('finish', () => {
          const buffer = fs.readFileSync(filePath);
          const sha256 = createHash('sha256').update(buffer).digest('hex');
          
          resolve({
            id: `pdf_${Date.now()}`,
            jobId,
            type: 'CALCULATION_SHEET',
            filePath,
            sha256,
            createdAt: new Date().toISOString(),
            sizeBytes: buffer.length
          });
        });
        
        stream.on('error', (error) => {
          reject(new Error(`PDF_GENERATION_ERROR: ${error.message}`));
        });
        
      } catch (error: any) {
        reject(new Error(`PDF_GENERATION_ERROR: ${error.message}`));
      }
    });
  }

  /**
   * Verify a generated PDF artifact
   */
  verifyArtifact(artifact: PDFArtifact): { valid: boolean; expected: string; actual: string } {
    if (!fs.existsSync(artifact.filePath)) {
      throw new Error(`FILE_NOT_FOUND: ${artifact.filePath}`);
    }
    
    const buffer = fs.readFileSync(artifact.filePath);
    const actual = createHash('sha256').update(buffer).digest('hex');
    
    return {
      valid: actual === artifact.sha256,
      expected: artifact.sha256,
      actual
    };
  }
}

export const pdfGenerator = new PDFGenerator();
