import { createHash } from 'crypto';
import { randomUUID } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import pino from 'pino';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import * as xlsx from 'xlsx';

const logger = pino();

export type DeliverableType = 'DOCX' | 'XLSX' | 'PDF' | 'PPTX';

export interface ArtifactRecord {
  id: string;
  jobId: string;
  type: DeliverableType;
  filename: string;
  sha256: string;
  templateVersion: string;
  generatorVersion: string;
  executionId: string;
  createdAt: string;
  citationIds: string[];
  sizeBytes: number;
}

/** All generated artifacts stored in-memory; would persist to DB/object store in production */
const artifactStore = new Map<string, ArtifactRecord>();

export class DeliverableService {
  private outDir: string;

  constructor() {
    this.outDir = process.env.ARTIFACTS_DIR ?? path.join(process.cwd(), 'artifacts');
    if (!fs.existsSync(this.outDir)) fs.mkdirSync(this.outDir, { recursive: true });
  }

  /** Generate a real DOCX file using docx package */
  async generateReport(
    jobId: string,
    title: string,
    sections: { heading: string; body: string }[],
    citations: { documentTitle: string; location: string; excerpt: string }[],
    executionId: string
  ): Promise<ArtifactRecord> {
    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({ text: `SIH 2026 Sovereign AI Workbench — Generated Report`, heading: HeadingLevel.TITLE }),
            new Paragraph({ text: `Title: ${title}`, heading: HeadingLevel.HEADING_1 }),
            new Paragraph({ text: `Generated: ${new Date().toISOString()}` }),
            new Paragraph({ text: `NOTE: This document was generated by an AI-assisted system. All engineering conclusions must be independently verified.` }),
            ...sections.flatMap(s => [
              new Paragraph({ text: s.heading, heading: HeadingLevel.HEADING_2 }),
              new Paragraph({ text: s.body })
            ]),
            ...(citations.length > 0 ? [
              new Paragraph({ text: "Citations", heading: HeadingLevel.HEADING_2 }),
              ...citations.map(c => new Paragraph({ text: `[${c.documentTitle}] at ${c.location}: "${c.excerpt.slice(0, 120)}..."`, bullet: { level: 0 } }))
            ] : [])
          ],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    return this.writeArtifact(jobId, 'DOCX', `report_${jobId}.docx`, buffer, '1.0.0', executionId, citations.map((_, i) => `cit-${i}`));
  }

  /** Generate a real XLSX file using xlsx package */
  async generateWorkbook(
    jobId: string,
    title: string,
    rows: Record<string, any>[],
    executionId: string
  ): Promise<ArtifactRecord> {
    if (rows.length === 0) throw new Error('INPUT_ERROR: rows cannot be empty');
    const ws = xlsx.utils.json_to_sheet(rows);
    const wb = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, "Data");
    const buffer = xlsx.write(wb, { type: "buffer", bookType: "xlsx" });
    return this.writeArtifact(jobId, 'XLSX', `workbook_${jobId}.xlsx`, buffer, '1.0.0', executionId, []);
  }

  getArtifact(id: string): ArtifactRecord | undefined {
    return artifactStore.get(id);
  }

  listArtifacts(jobId: string): ArtifactRecord[] {
    return Array.from(artifactStore.values()).filter(a => a.jobId === jobId);
  }

  verifyArtifact(id: string): { valid: boolean; expected: string; actual: string } {
    const record = artifactStore.get(id);
    if (!record) throw new Error(`ARTIFACT_ERROR: Artifact ${id} not found`);
    const filePath = path.join(this.outDir, record.filename);
    const fileContent = fs.readFileSync(filePath);
    const actual = createHash('sha256').update(fileContent).digest('hex');
    return { valid: actual === record.sha256, expected: record.sha256, actual };
  }

  private buildReportText(
    title: string,
    sections: { heading: string; body: string }[],
    citations: { documentTitle: string; location: string; excerpt: string }[]
  ): string {
    const lines: string[] = [
      `SIH 2026 Sovereign AI Workbench — Generated Report`,
      `Title: ${title}`,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `NOTE: This document was generated by an AI-assisted system.`,
      `All engineering conclusions must be independently verified.`,
      `---`,
      ``
    ];
    for (const s of sections) {
      lines.push(`## ${s.heading}`, s.body, '');
    }
    if (citations.length > 0) {
      lines.push('## Citations');
      for (const c of citations) {
        lines.push(`- [${c.documentTitle}] at ${c.location}: "${c.excerpt.slice(0, 120)}..."`);
      }
    }
    return lines.join('\n');
  }

  private async writeArtifact(
    jobId: string,
    type: DeliverableType,
    filename: string,
    content: string | Buffer,
    templateVersion: string,
    executionId: string,
    citationIds: string[]
  ): Promise<ArtifactRecord> {
    const filePath = path.join(this.outDir, filename);
    fs.writeFileSync(filePath, content);

    const buffer = fs.readFileSync(filePath);
    const sha256 = createHash('sha256').update(buffer).digest('hex');
    const sizeBytes = buffer.length;

    const record: ArtifactRecord = {
      id: randomUUID(),
      jobId,
      type,
      filename,
      sha256,
      templateVersion,
      generatorVersion: '1.0.0',
      executionId,
      createdAt: new Date().toISOString(),
      citationIds,
      sizeBytes
    };

    artifactStore.set(record.id, record);
    logger.info({ artifactId: record.id, jobId, filename, sha256 }, 'Artifact created');
    return record;
  }
}

export const deliverableService = new DeliverableService();
